# Generated by Django 2.0.5 on 2018-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigBasket', '0006_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
