# Generated by Django 2.0.5 on 2018-08-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigBasket', '0010_auto_20180803_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
