# Generated by Django 2.0.5 on 2018-08-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigBasket', '0011_auto_20180804_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_quantity',
            new_name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='product_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
