# Generated by Django 2.0.5 on 2018-08-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigBasket', '0014_auto_20180805_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
